### PR TITLE
alternative getUniforms API

### PR DESCRIPTION
**Pull request by rolyatmax**
Having `forEachUniform` call a user-supplied function synchronously seems like an awkward way to essentially just return some uniforms and their values to the user. It also might imply that there's something fancy going on behind the scenes which requires calling the user-supplied function asynchronously or calling them in a particular order. I wonder if returning an object would be more straight-forward.

I don't feel too strongly about this, but figured I'd open the PR so there's a place to have that conversation, even if it's just a quick one!

### CODE REVIEW

**Comment by tsherif** [comment]
I did it this way in an early version, but my thinking is that when you return the values, there's an implication that the returned values belong to the application, which isn't really the case here since I'm returning pre-allocated arrays. The callback to me suggests that the values passed are only valid while the callback is executing.

I'm happy to hear alternatives though, as I'm not in love with this solution. If there was an easy way to have the application pass "out" buffers, I'd go with that, but that seems really awkward in this case.

**Comment by rolyatmax** [comment]
Yeah, I see what you mean. I imagine some people might be forced to hold onto the values after all the callbacks are called in order to supply the uniforms to their framework-of-choice with a single object. E.g.:

```js
const uniforms = {}
forEachUniform(lng, lat, zoom, view, proj, (name, value) => {
  uniforms[name] = value
})
myGLFramework.draw(uniforms)
```

I kinda wonder if I'd even worry about users holding onto those returned arrays. If you allocated some arrays to be reused _only by this function_, then you could be sure that the values in the returned arrays would stay fresh up until they call the `getUniforms` function again. That personally doesn't seem so bad.

You could also let the user pass a flag to the function to indicate it wants fresh arrays created and returned. That seems kinda messy, though. 🤔 Might be veering too far towards "support every possible use case" / "be flexible at all costs", hahaha.

**Comment by tsherif** [comment]
Ah that's a good point. I was thinking too much in terms of PicoGL's API where the uniforms are set individually. 

I'll meet you halfway. I'll change the function to be something like this:
```js
   PicoMercator.uniforms(..., (uniforms) => {...})
```
Where `uniforms` will be uniform name/value pairs.

**Comment by rolyatmax** [comment]
I'll take it!

**Comment by rolyatmax** [comment]
Looks like this was updated in https://github.com/tsherif/pico-mercator/commit/f894ee73ac2882b1efa811db8e391f326aa4b962 - thanks!

**Pull request closed without merging**
